# Generated by Django 5.1.4 on 2025-01-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetails',
            name='assigned_to',
        ),
    ]
